### ISSUE TITLE
謝謝你的心得

### ISSUE THREAD

**Issue by azole** [qq201234/git-workshop#2]
「我會用心撐下去、努力學習」 -> 會的，人類會自證預言，或者又稱自我實現預言，當你說自己辦得到的時候，你就會去想辦法做到，當你說自己辦不到的時候，其實也已經是在變相地給自己留了後路了，所以，很高興你給自己一個正面的預言，就讓我們一起去實現它！

另外，我也很贊同你在影片心得中提到的，能來這個班的同學，其實已經成功一半了，我一直覺得這樣的轉職班，課程安排、老師指導這些是一回事，最重要的其實是同學，我帶了好幾個班，班上討論氛圍旺盛的、願意互相幫忙、互相分享的，這個班級的進步幅度都會是比較巨大的，目前第一天上課感覺起來，你們都有很多好的徵兆，我也上得很開心～ 可以的話，上課多跟我互動喔，我問的問題，試著回答看看，答對答錯一點都不重要，而且答錯才是收穫最多的人，因為獲得了不同的想法、成長了！

分享一下我自己很喜歡的圖片：我一直覺得轉換領域，或者所有的學習成長都是，我們試著在改變自己，改變自己的過程從來都是辛苦的，但要堅持下去，就可以變成自己更想要的那個樣子。
<img width="529" alt="image" src="https://user-images.githubusercontent.com/2560515/203016657-748533f0-91f7-4796-b39b-9abfb55b0252.png">

**Comment by qq201234** [comment]
謝謝老師！ 老師 妳很正面、也很有能量，很能夠感受得到力量呢！！

「答錯才是收穫最多的人，因為獲得了不同的想法、成長了！」->
我會試著努力答題看看的！雖然目前還有很多地方沒有那麼深入瞭解，但真的很期待未來的課程。

這張圖片真的很貼切，我很喜歡，謝謝老師！
跟從前的自己比較起來，目前的生活真的感到很充實、很開心，雖然並不是指有多喜歡打code啦 xD
而且也不知道後來的業界生活是什麼？但也無所謂。不只認識了老師、也更認識了自己感到很高興！

看了老師在賴群分享的影片，我感覺非常受用！！我以前就是常常後悔自己走的路，不確定到底正不正確，
因為總覺得已經比正常人晚起步很多了，不能再浪費太多時間了。
後悔當初怎麼沒有去讀資訊相關科系、
後悔這個年紀已經比正常的應屆畢業生高太多了、
後悔自己不是個很能夠表達自我的人、
無限後悔 無限迴圈。

但！現在都不會這樣想了，即便未來轉職沒有辦法那麼順利，也不會感到後悔！因為我真的很滿意我現在的狀態，充滿了好的能量，非常感謝老師把很多很好的能量分享給我們！

**Comment by azole** [comment]
讓自己處於正面循環中很重要，在正面循環中，會比較有力氣努力 -> 努力有好的回報 -> 又會更有力氣努力，人難免偶爾會陷入負面循環，但一定要有意識知道這件事，然後把自己拉出來。總之，恭喜你現在在正面循環中，繼續加油～
